/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AthleteService } from "../athlete.service";
import { AthleteCreateInput } from "./AthleteCreateInput";
import { Athlete } from "./Athlete";
import { AthleteFindManyArgs } from "./AthleteFindManyArgs";
import { AthleteWhereUniqueInput } from "./AthleteWhereUniqueInput";
import { AthleteUpdateInput } from "./AthleteUpdateInput";
import { ResultFindManyArgs } from "../../result/base/ResultFindManyArgs";
import { Result } from "../../result/base/Result";
import { ResultWhereUniqueInput } from "../../result/base/ResultWhereUniqueInput";

export class AthleteControllerBase {
  constructor(protected readonly service: AthleteService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Athlete })
  async createAthlete(
    @common.Body() data: AthleteCreateInput
  ): Promise<Athlete> {
    return await this.service.createAthlete({
      data: data,
      select: {
        age: true,
        createdAt: true,
        gender: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Athlete] })
  @ApiNestedQuery(AthleteFindManyArgs)
  async athletes(@common.Req() request: Request): Promise<Athlete[]> {
    const args = plainToClass(AthleteFindManyArgs, request.query);
    return this.service.athletes({
      ...args,
      select: {
        age: true,
        createdAt: true,
        gender: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Athlete })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async athlete(
    @common.Param() params: AthleteWhereUniqueInput
  ): Promise<Athlete | null> {
    const result = await this.service.athlete({
      where: params,
      select: {
        age: true,
        createdAt: true,
        gender: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Athlete })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAthlete(
    @common.Param() params: AthleteWhereUniqueInput,
    @common.Body() data: AthleteUpdateInput
  ): Promise<Athlete | null> {
    try {
      return await this.service.updateAthlete({
        where: params,
        data: data,
        select: {
          age: true,
          createdAt: true,
          gender: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Athlete })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAthlete(
    @common.Param() params: AthleteWhereUniqueInput
  ): Promise<Athlete | null> {
    try {
      return await this.service.deleteAthlete({
        where: params,
        select: {
          age: true,
          createdAt: true,
          gender: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/results")
  @ApiNestedQuery(ResultFindManyArgs)
  async findResults(
    @common.Req() request: Request,
    @common.Param() params: AthleteWhereUniqueInput
  ): Promise<Result[]> {
    const query = plainToClass(ResultFindManyArgs, request.query);
    const results = await this.service.findResults(params.id, {
      ...query,
      select: {
        athlete: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        event: true,
        id: true,

        meet: {
          select: {
            id: true,
          },
        },

        place: true,
        time: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/results")
  async connectResults(
    @common.Param() params: AthleteWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        connect: body,
      },
    };
    await this.service.updateAthlete({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/results")
  async updateResults(
    @common.Param() params: AthleteWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        set: body,
      },
    };
    await this.service.updateAthlete({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/results")
  async disconnectResults(
    @common.Param() params: AthleteWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        disconnect: body,
      },
    };
    await this.service.updateAthlete({
      where: params,
      data,
      select: { id: true },
    });
  }
}
