/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SeasonService } from "../season.service";
import { SeasonCreateInput } from "./SeasonCreateInput";
import { Season } from "./Season";
import { SeasonFindManyArgs } from "./SeasonFindManyArgs";
import { SeasonWhereUniqueInput } from "./SeasonWhereUniqueInput";
import { SeasonUpdateInput } from "./SeasonUpdateInput";
import { MeetFindManyArgs } from "../../meet/base/MeetFindManyArgs";
import { Meet } from "../../meet/base/Meet";
import { MeetWhereUniqueInput } from "../../meet/base/MeetWhereUniqueInput";

export class SeasonControllerBase {
  constructor(protected readonly service: SeasonService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Season })
  async createSeason(@common.Body() data: SeasonCreateInput): Promise<Season> {
    return await this.service.createSeason({
      data: data,
      select: {
        createdAt: true,
        endDate: true,
        id: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Season] })
  @ApiNestedQuery(SeasonFindManyArgs)
  async seasons(@common.Req() request: Request): Promise<Season[]> {
    const args = plainToClass(SeasonFindManyArgs, request.query);
    return this.service.seasons({
      ...args,
      select: {
        createdAt: true,
        endDate: true,
        id: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Season })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async season(
    @common.Param() params: SeasonWhereUniqueInput
  ): Promise<Season | null> {
    const result = await this.service.season({
      where: params,
      select: {
        createdAt: true,
        endDate: true,
        id: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Season })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSeason(
    @common.Param() params: SeasonWhereUniqueInput,
    @common.Body() data: SeasonUpdateInput
  ): Promise<Season | null> {
    try {
      return await this.service.updateSeason({
        where: params,
        data: data,
        select: {
          createdAt: true,
          endDate: true,
          id: true,
          name: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Season })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSeason(
    @common.Param() params: SeasonWhereUniqueInput
  ): Promise<Season | null> {
    try {
      return await this.service.deleteSeason({
        where: params,
        select: {
          createdAt: true,
          endDate: true,
          id: true,
          name: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/meets")
  @ApiNestedQuery(MeetFindManyArgs)
  async findMeets(
    @common.Req() request: Request,
    @common.Param() params: SeasonWhereUniqueInput
  ): Promise<Meet[]> {
    const query = plainToClass(MeetFindManyArgs, request.query);
    const results = await this.service.findMeets(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        id: true,
        location: true,
        name: true,

        season: {
          select: {
            id: true,
          },
        },

        series: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/meets")
  async connectMeets(
    @common.Param() params: SeasonWhereUniqueInput,
    @common.Body() body: MeetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      meets: {
        connect: body,
      },
    };
    await this.service.updateSeason({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/meets")
  async updateMeets(
    @common.Param() params: SeasonWhereUniqueInput,
    @common.Body() body: MeetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      meets: {
        set: body,
      },
    };
    await this.service.updateSeason({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/meets")
  async disconnectMeets(
    @common.Param() params: SeasonWhereUniqueInput,
    @common.Body() body: MeetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      meets: {
        disconnect: body,
      },
    };
    await this.service.updateSeason({
      where: params,
      data,
      select: { id: true },
    });
  }
}
